version: '3'
services: 
    python:
        container_name: python3.6.8-ASA
        build:
          context: .
        tty: true
        volumes:
        - ./:/root
        ports:
        - "5000:5000"